### PR TITLE
remove STORM paper specific experiment dir and readme from main branch

### PR DESCRIPTION
**Pull request by Yucheng-Jiang**
As title, remove ./FreshWiki,  ./eval and NAACL replicate experiments instructions in README from main branch as they are duplicates in NAACL-BACKUP branch.

Action item: I will copy FreshWiki license to NAACL backup branch in a separate commit.

### CODE REVIEW

**Comment by shaoyijia** [comment]
Could you add a Dataset section in README.md so people can know our project also contributes datasets?

**Comment by Yucheng-Jiang** [comment]
> Could you add a Dataset section in README.md so people can know our project also contributes datasets?

Sure! Will resolve it in in PR #185

**Comment by shaoyijia** [comment]
We could maintain them in branches. Could we also make a zip file and upload to our project google drive and share the link? In this way, people can directly download the zip file if they don't want to checkout the branches.

**Review by shaoyijia — APPROVED** [review]

**Comment by Yucheng-Jiang** [comment]
Sounds good!

**Pull request merged**
