### PR TITLE
Update engine.py

### PR DESCRIPTION
**Pull request by r0cketdyne**
Refined the code by improving readability, organizing imports, adding docstrings, and renaming some variables for clarity. Additionally, I used dataclasses to define the argument structure, making it more concise and maintainable. I also ensured consistent formatting and adhered to PEP 8 guidelines, enhancing code consistency and readability.

### CODE REVIEW

**Review by arman-hk — COMMENTED** [review]
## ⚠️
This is a destructive pull request.

**Comment by r0cketdyne** [comment]
Can you say more? If you have the data please put it in.

**Comment by arman-hk** [comment]
## ⚠️

Hey @shaoyijia, it looks like this PR have removed critical chunks (`-261`) of the code responsible for persona-based conversational data gathering and subsequent content generation (outline + article generation).

Can you review and if approved, I recommend closing this PR to maintain functionality.

**Review by Octobot222 — APPROVED** [review]

**Comment by Yucheng-Jiang** [comment]
@r0cketdyne Thanks for your interest in our project! Could you justify the reason for deleting functionality of perspective guided QA conversation and outline generation?

**Pull request closed without merging**
