### PR TITLE
Use `black` as the python code formatter.

### PR DESCRIPTION
**Pull request by shaoyijia**
1. Set up `black` code formatter for this repo to ensure code quality. Update `README.md` and `CONTRIBUTING.md` accordingly.
2. Reformat `knowledge_storm/` using `black`.

### CODE REVIEW

**Review by Yucheng-Jiang — COMMENTED** [review]
I'm thinking about following workflow: 

- Require each developer to install pre-commit hook to enforce running the code formatter automatically upon every commit. Documentation: https://pre-commit.com.
- Add main branch protection by running "check style" script, to enforce all incoming code is properly formatted.

Rationale for using combination of these two method:
1. Developers do not need to manually run code formatter every time
2. When developers properly configure pre-commit hook, everything will be automatic; when they haven't configure pre-commit hook, the branch protection will reject merge action.
3. There is option to setup CI/CD workflow to auto run code formatter, but it will create code formatting commit upon every push, which I think it's not neat? But not a big concern.

**Comment by shaoyijia** [comment]
> but it will create code formatting commit upon every push

Yes, I also think this is not neat. Previously, I also found [an unofficial action](https://github.com/marketplace/actions/run-black-formatter) that can also reformat the code based on the identified format issue. But I think the change will not be transparent enough to developer and they may fail to test the reformatted code (reformatting the code shall be safe, but just in case).

> Require each developer to install pre-commit hook

I can see the benefit, but given this repo mainly hosts a python package, will this "overkill"? Also, I am not sure if everyone is familiar with this.

**Comment by Yucheng-Jiang** [comment]
For pre-hook, on our end we just need to add `.pre-commit-config.yaml`. For the developers, they only need to do
```bash
pip install pre-commit
pre-commit install
```
Upon commit, it will run code formatter automatically.

**Comment by shaoyijia** [comment]
ok, I will look into this. Thanks

**Review by Yucheng-Jiang — APPROVED** [review]

**Pull request merged**
